version: "3.7"

services:
  app:
    build: .
    ports:
      - "8081:8081"
    networks:
      - configstore_tux_network
    environment:
      MONGO_URL: mongodb://mongodb:27017
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27018:27017"
    networks:
      - configstore_tux_network
    volumes:
      - monogo-user-data:/data/db
volumes:
  monogo-user-data:
networks:
  configstore_tux_network:
    external: true